version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks: 
      - app-network
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: product-service:latest
    container_name: product-service
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - app-network
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/productdb
      - SPRING_RABBITMQ_HOST=rabbitmq

networks:
  app-network:
    driver: bridge